name: arogya_direct
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  custom_info_window: ^1.0.1
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.8
  firebase_database: ^10.2.2
  firebase_core: ^2.13.1
  geolocator:
  maps_toolkit: ^2.0.1
  flutter_local_notifications: ^5.0.0+1
  rxdart : ^0.27.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


assets:
   - assets/